NittCalendar/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('events/', include('events.urls', namespace="events")),
]

events/urls.py
from django.urls import path

from .views import (EventsListView, EventCreateView, EventEditView,
                    EventDeleteView, CategoryCreateView, EventsCalendarView,
                    EventApproveView, CategoryDeleteView)

app_name = "events"

urlpatterns = [
    path('', EventsListView.as_view(), name="events_list"),
    path('calendar', EventsCalendarView.as_view(), name="events_calendar"),
    path('create', EventCreateView.as_view(), name="event_create"),
    path('edit/<int:event_id>', EventEditView.as_view(), name="event_edit"),
    path('approve/<int:event_id>', EventApproveView.as_view(), name="event_approve"),
    path('delete/<int:event_id>', EventDeleteView.as_view(), name="event_delete"),
    path('category/create', CategoryCreateView.as_view(), name="category_create"),
    path('category/delete', CategoryDeleteView.as_view(), name="category_delete"),
]

events/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True) 

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    start = models.DateTimeField(auto_now=False, auto_now_add=False)
    end = models.DateTimeField(auto_now=False, auto_now_add=False)
    venue = models.CharField(max_length=100)
    image = models.ImageField(upload_to='events', blank=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

events/forms.py
from django.forms import Form, ModelForm, ModelChoiceField

from .models import *


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ["name"]


class EventForm(ModelForm):
    class Meta:
        model = Event
        exclude = ['approved']

class CategoryDeleteForm(Form):
    category = ModelChoiceField(queryset=Category.objects.all(), required=True)

events/views.py
from json import dumps
from datetime import datetime

from django.http import HttpResponse, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.forms.models import model_to_dict
from django.contrib.staticfiles.templatetags.staticfiles import static

from .forms import CategoryForm, EventForm, CategoryDeleteForm
from .models import Category, Event
from .helpers import is_admin, admin_route


class EventsListView(View):
    def get(self, request):
        events = Event.objects.filter(end__gte=datetime.now()).order_by('start')
        message = request.GET.get("message", "")
        return render(request, 'events_list.html', {
            'events': events,
            'is_admin': is_admin(request),
            'display_message': message
        })

class EventsCalendarView(View):
    def get(self, request):
        events = Event.objects.all()
        calendar_event_objects = []

        for event in events:
            image = event.image.url if event.image else static('images/default-image.png')
            calendar_event_objects.append({
                'id': event.id,
                'title': event.name,
                'start': event.start.isoformat(),
                'end': event.end.isoformat(),
                'start_display': event.start.strftime("%b. %d, %Y, %I:%M %p"),
                'end_display': event.end.strftime("%b. %d, %Y, %I:%M %p"),
                'image': image,
                'description': event.description,
                'venue': event.venue,
                'category': event.category.name
            })

        return render(request, 'calendar.html', {
            'calendar_events': dumps(calendar_event_objects)
        })


class EventCreateView(View):
    def get(self, request):
        form = EventForm()
        title = "Create New Event"
        return render(request, 'event.html', {'form': form, 'title': title})

    def post(self, request):
        form = EventForm(request.POST, request.FILES)
        try:
            if is_admin(request):
                form = form.save(commit=False)
                form.approved = True
            form.save()
        except ValueError as e:
            title = "Create New Event"
            return render(request, 'event.html', {'form': form, 'title': title})

        if is_admin(request):
           return redirect('events:events_list') 

        message = "Event has been created. Event will be publicly visible after an admin approves it."
        return redirect(reverse("events:events_list")+"?message="+message)


@method_decorator(admin_route, name='dispatch')
class EventApproveView(View):
    def get(self, request, event_id):
        try:
            event = Event.objects.get(pk=event_id)    
            event.approved = True
            event.save()
            return redirect('events:events_list')
        except:
            return redirect('events:events_list')


@method_decorator(admin_route, name='dispatch')
class EventEditView(View):
    def get(self, request, event_id):

        try:
            event = Event.objects.get(pk=event_id)
        except:
            return redirect('events:events_list')

        form = EventForm(instance=event)
        title = "Edit Event"

        return render(request, 'event.html', {'form': form, 'title': title})

    def post(self, request, event_id):
        try:
            event = Event.objects.get(pk=event_id)
        except:
            return redirect('events:events_list')

        form = EventForm(request.POST, request.FILES, instance=event)
        try:
            form.save()
        except ValueError as e:
            title = "Edit Event"
            return render(request, 'event.html', {'form': form, 'title': title})

        return redirect('events:events_list')


@method_decorator(admin_route, name='dispatch')
class EventDeleteView(View):
    def get(self, request, event_id):
        try:
            event = Event.objects.get(pk=event_id)
            event.delete()
            return redirect('events:events_list')
        except:
            return redirect('events:events_list')

@method_decorator(admin_route, name='dispatch')
class CategoryCreateView(View):
    def get(self, request):
        form = CategoryForm()
        title = "Create New Category"
        return render(request, 'event.html', {'form': form, 'title': title})

    def post(self, request):
        form = CategoryForm(request.POST)
        try:
            form.save()
        except ValueError as e:
            title = "Create New Category"
            return render(request, 'event.html', {'form': form, 'title': title})

        return redirect('events:events_list')

@method_decorator(admin_route, name='dispatch')
class CategoryDeleteView(View):
    def get(self, request):
        form = CategoryDeleteForm()
        title = "Delete Existing Category"
        caution = "(Deleting a category deletes all the events in that category)"
        return render(request, 'event.html', {'form': form, 'title': title, 'caution': caution})

    def post(self, request):
        form = CategoryDeleteForm(request.POST)
        if form.is_valid():
            category = form.cleaned_data.get('category')
            category.delete()
            return redirect('events:events_list')
        else:
            print(form.errors)
            title = "Delete Existing Category"
            caution = "(Deleting a category deletes all the events in that category)"
            return render(request, 'event.html', {'form': form, 'title': title, 'caution': caution})

        return redirect('events:events_list')

events/templates/admin_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Events Calendar</title>

    <link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.min.css" %}" rel="stylesheet">
    <script src="{% static "js/jquery.min.js" %}"></script>    
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="" class="site_title"><i class="fa fa-calendar"></i> <span>Calendar</span></a>
            </div>

            <div class="clearfix"></div>

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Events <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'events:events_list' %}">View Events</a></li>
                      <li><a href="{% url 'events:event_create' %}">Create Events</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i> Category <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'events:category_create' %}">Add Category</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{% static "images/user.png" %}" alt="">Admin
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="#"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          {% block content %}
          {% endblock %}
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Made with <font color="red">&hearts;</font> by <a href="https://deltaforce.club">Delta Force</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <script src="{% static "js/moment.min.js" %}"></script>    
    <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
    <script src="{% static "js/custom.min.js" %}"></script>
	
  </body>
</html>

events/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Events Calendar | NIT-Trichy</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "landing/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "landing/css/new-age.css" %}" rel="stylesheet">
    <link href="{% static "landing/css/cards.min.css" %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <header class="masthead">
      <div class="container">
        <div style="float:right; margin-bottom:20px;" class="row">
          <a class="btn btn-success btn-md" href="{% url 'events:event_create' %}">Create Event</a>
          {% if is_admin %}
          <a class="btn btn-success btn-md" href="{% url 'events:category_create' %}">Create Category</a>
          <a class="btn btn-success btn-md" href="{% url 'events:category_delete' %}">Delete Category</a>
          {% endif %}
        </div>
        <br />

        {% if display_message %}
        <div class="row alert alert-primary" style="width:100%; margin:20px;">
          {{display_message}}
        </div>
        {% endif %}

        <div class="row" style="width:100%; margin:0px;">
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </header>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "landing/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "landing/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "js/linkify.min.js" %}"></script>
    <script src="{% static "js/linkify-jquery.min.js" %}"></script>
  </body>

</html>

events/templates/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>NIT-Trichy | Events Calendar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">   
	<link href="{% static "landing/css/new-age.css" %}" rel="stylesheet">	
    <link href="{% static "calendar/fullcalendar.css" %}" rel="stylesheet">      
	<link href="{% static "calendar/custom.css" %}" rel="stylesheet">    
    <script src="{% static "js/jquery.min.js" %}"></script>    
    <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
	<script src="{% static "calendar/custom.js" %}" rel="stylesheet"></script>
	<script src="{% static "js/linkify.min.js" %}"></script>
    <script src="{% static "js/linkify-jquery.min.js" %}"></script>
</head>


<script>

	$(document).ready(function() {
		var calendar =  $('#calendar').fullCalendar({
			header: {
				left: 'title',
				center: 'agendaWeek,month',
				right: 'prev,next today'
			},
			editable: false,
			firstDay: 1, //  1(Monday) this can be changed to 0(Sunday) for the USA system
			selectable: false,
			defaultView: 'month',
			allDayDefault: false,
			axisFormat: 'mm:h',

			columnFormat: {
                month: 'ddd',    // Mon
                week: 'ddd d', // Mon 7
                day: 'dddd M/d',  // Monday 9/7
                agendaDay: 'dddd d'
            },
            titleFormat: {
                month: 'MMMM yyyy', // September 2009
                week: "MMMM yyyy", // September 2009
                day: 'MMMM yyyy'                  // Tuesday, Sep 8, 2009
            },
			allDaySlot: false,
			selectHelper: true,
			select: function(start, end, allDay) {
			},
			droppable: false, // this allows things to be dropped onto the calendar !!!	
			events: JSON.parse("{{calendar_events}}".replace(/&quot;/g,'"').replace(/(\r\n|\n)/g, "<br />")),
			eventClick: function(event, jsEvent, view) {
				$("#event-title").html(event.title);
				$("#event-image").attr('src', event.image);
				$("#event-description").html(event.description);
				$("#event-description").linkify();
				$("#event-timings").html("<b>Timings</b> : " + (event.start_display) + " to " + (event.end_display));
				$("#event-category").html("<b>Category</b> : " + event.category);
				$("#event-venue").html("<b>Venue</b> : " + event.venue);
				$("#event-modal").modal('show');
			},
		});
		
		
	});

</script>
</head>
<body>
	<div id='wrap'>
		<div id='calendar'></div>
		<div style='clear:both'></div>
		<div id="event-modal" class="modal fade" role="dialog" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="event-title"></h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body" style="text-align:left;">
					<center>
						<img class="img-responsive" id="event-image" src="" style="margin-bottom: 20px;">
						<h5 style="margin-bottom: 20px; word-wrap: break-word;" id="event-description"></h5>
					</center>
					<p id="event-timings"></p>
					<p id="event-venue"></p>
					<p id="event-category"></p>
				</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

events/templates/event.html
{% load static %}

{% include 'material/includes/material_css.html' %}
<!--<script src="{% static 'material/js/jquery.js' %}"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% include 'material/includes/material_js.html' %}

{% load material_form %}
<div class="container expand-on-small-only">
    <div class="row">
        <div class="col s12 m8 l8 offset-m2 offset-l2">
                <div class="card">
                    <form method="POST" enctype="multipart/form-data">
                        <div class="card-content">
                            <span class="card-title grey-text text-darken-2">{{title}}</span>
                            <p class="red-text text-darken-2" style="margin-bottom:8px;">{{caution}}</p>
                            {% csrf_token %}
                            {% form form=form %}{% endform %}
                        </div>
                        <div class="card-action">
                            <button type="submit" name="submit" class="btn">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
    </div>
</div>

events/templates/event_delete.html
{% extends 'admin_base.html' %}

{% block content %}
    <center>
        <p style="font-size: 20px;">Do you want to delete <b>{{event.name}}</b>?</p>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger">Delete</button>
        </form>
    </center>
{% endblock %}

events/templates/events_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% for event in events %}
        {%if is_admin or event.approved %}
            <div class="col-md-6 col-lg-4" style="margin-bottom: 15px;">
                <div class="card">
                    {%if event.image %}
                        <img class="img-fluid" src="{{event.image.url}}" alt="Card image cap">
                    {% else %}
                        <img class="img-fluid" src="{% static "images/default-image.png" %}" alt="Card image cap">
                    {% endif %}
                        <div class="card-body">
                        <h4 class="card-title">{{event.name}}</h4>
                        <h5 class="card-text" style="font-size:14px;font-weight: bold;">{{event.start}}, {{event.venue}}</h5>
                        <p class="card-text">{{event.category}}</p>
                        <a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal-{{event.id}}">More Details</a>
                        {%if is_admin %}
                            {% if not event.approved %}
                                <a class="btn btn-warning btn-sm" onclick="displayAlertDialog('Approve', '{% url 'events:event_approve' event_id=event.id %}');">Approve</a>
                            {% endif %}
                            <a class="btn btn-danger btn-sm" onclick="displayAlertDialog('Delete', '{% url 'events:event_delete' event_id=event.id %}');">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="modal-{{event.id}}" class="modal fade" role="dialog" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">{{event.name}}</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <center>
                            {%if event.image %}
                                <img class="img-fluid" src="{{event.image.url}}" style="margin-bottom: 20px;">
                            {% else %}
                                <img class="img-fluid" src="{% static "images/default-image.png" %}" style="margin-bottom: 20px;">
                            {% endif %}
                            <h5 style="margin-bottom: 20px; word-wrap: break-word;" data-linkify="this">{{event.description|linebreaksbr}}</h5>
                        </center>
                        <p><b>Timings : </b> {{event.start}} to {{event.end}}</p>
                        <p><b>Venue : </b> {{event.venue}}</p>
                        <p><b>Category : </b> {{event.category}}</p>
                    </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    <div id="modal-alert-dialog" class="modal fade" role="dialog" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            <div class="modal-body">
                <p id="modal-alert-content"></p>
                <center>
                    <a data-dismiss="modal" class="btn special-color-dark btn-sm" href="#">Cancel</a>
                    <a id="modal-alert-anchor" class="btn btn-primary btn-sm" href="#">Continue</a>
                </center>
            </div>
            </div>
        </div>
    </div>
    <script>
        function displayAlertDialog(action, url) {
            var content = "Do you want to " + action + " the event?";
            $('#modal-alert-content').html(content);
            $('#modal-alert-anchor').attr('href', url);
            $('#modal-alert-dialog').modal();
        }
    </script>
{% endblock %}